var app= angular.module('MyUSBMovieApp',
  [
    'ngMorph',
    'ngRoute',
    'ngMaterial',
    'angular-svg-round-progress',
  ]);


app.constant("Parameters", {
    "separators": ["\\.","\\-","_",],
    "uselessWords": ["720p",
                    "1080p",
                    "dvdrip",
                    "yify",
                    "x264",
                    "HD",
                    "m720p",
                    "aac",
                    "ac3",
                    "dts",
                    "xvid",
                    "truefrench",
                    "vf",
                    "vo",
                    "vff",
                    "multi",
                    "vost",
                    "acc",
                    "5.1",
                    "web",
                    "dl",
                    "mkv",
                    "\\[",
                    "\\]",
                    "bluray",
                    "brrip",
                    "www\\..*\\.com",
                    "h264",
                    "mp4",
                    ],
    "extensions" : ["mkv","avi","mp4","flv"],
    "directory" : "/Users/joris/Downloads/Folx/movie/",
    "successRename" : "The file has been renamed with success !",
    "failRename" : "An error occured when renaming the file !",
    "successHideFile" : "The file has been hidden from the app with success !",
    "failHideFile" : "An error occured when hidding the file !",
});
