app.controller('HomeCtrl', ['$scope','$rootScope', function ($scope,$rootScope) {
  $rootScope.example1 = {
    closeEl: '.close',
    modal: {
      templateUrl: 'app/components/modal/loginform.html'
    }
  };


$scope.movieList = [{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
},{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
},{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
},{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
},{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
},{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
},{
 "Title":"Fury",
 "Year":"2014",
 "Rated":"R",
 "Released":"17 Oct 2014",
 "Runtime":"134 min",
 "Genre":"Action, Drama, War",
 "Director":"David Ayer",
 "Writer":"David Ayer",
 "Actors":"Brad Pitt, Shia LaBeouf, Logan Lerman, Michael Peña",
 "Plot":"April, 1945. As the Allies make their final push in the European Theatre, a battle-hardened army sergeant named Wardaddy commands a Sherman tank and his five-man crew on a deadly mission behind enemy lines. Out-numbered, out-gunned, and with a rookie soldier thrust into their platoon, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
 "Language":"English, German",
 "Country":"UK, China, USA",
 "Awards":"4 wins & 9 nominations.",
 "Poster":"assets/img/fury.jpg",
 "Metascore":"64",
 "imdbRating":"7.9",
 "imdbVotes":"89,030",
 "imdbID":"tt2713180",
 "Type":"movie",
 "Response":"True"
}];

}]);